import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Menu from "./components/menu";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const cyform = localFont({
    src: [
        {
            path: "../public/fonts/Cyform-DEMO.otf",
            weight: "400",
            style: "normal",
        },
    ],
    variable: "--font-cyform",
    display: "swap",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="fr"
            className={cyform.variable}
        >
            <body>
                <div
                    aria-hidden="true"
                    className="
          pointer-events-none fixed inset-0 -z-10
          bg-[linear-gradient(135deg,var(--bg-0),var(--bg-1)_45%,#001d18_70%,var(--bg-0))]
        "
                >
                    <div className="absolute inset-0 bg-[var(--bg-0)/40]" />
                </div>
                <Menu />
                {children}
            </body>
        </html>
    );
}
